[2025-03-23T19:24:13.991+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T19:24:14.009+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.run_dvc_pipeline manual__2025-03-23T19:10:07.337326+00:00 [queued]>
[2025-03-23T19:24:14.017+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.run_dvc_pipeline manual__2025-03-23T19:10:07.337326+00:00 [queued]>
[2025-03-23T19:24:14.019+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-23T19:24:14.042+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_dvc_pipeline> on 2025-03-23 19:10:07.337326+00:00
[2025-03-23T19:24:14.051+0000] {standard_task_runner.py:72} INFO - Started process 231 to run task
[2025-03-23T19:24:14.055+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'run_dvc_pipeline', 'manual__2025-03-23T19:10:07.337326+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpfs28zgo4']
[2025-03-23T19:24:14.058+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask run_dvc_pipeline
[2025-03-23T19:24:14.082+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-23T19:24:14.138+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.run_dvc_pipeline manual__2025-03-23T19:10:07.337326+00:00 [running]> on host 22e98b2d0fd5
[2025-03-23T19:24:14.233+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='botorat3@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='run_dvc_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T19:10:07.337326+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T19:10:07.337326+00:00'
[2025-03-23T19:24:14.234+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-23T19:24:14.250+0000] {data_pipeline.py:54} INFO - Executing script: /opt/airflow/scripts/dvc_pipeline.py
[2025-03-23T19:24:16.783+0000] {data_pipeline.py:58} ERROR - Error executing /opt/airflow/scripts/dvc_pipeline.py: Command '['python', '/opt/airflow/scripts/dvc_pipeline.py']' returned non-zero exit status 1.
[2025-03-23T19:24:16.784+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-23T19:24:16.790+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-23T19:24:16.791+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=run_dvc_pipeline, run_id=manual__2025-03-23T19:10:07.337326+00:00, execution_date=20250323T191007, start_date=20250323T192414, end_date=20250323T192416
[2025-03-23T19:24:16.839+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T19:24:16.862+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T19:24:16.863+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
